name: smart_x
description: "app for college"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.2.0

  # State Management & UI
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  table_calendar: ^3.1.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0 # Added for premium loading effect
  flip_card: ^0.7.0
  fl_chart: ^0.68.0 # For beautiful charts
  glassmorphism: ^3.0.0


  # Local Storage & Permissions
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3

  # Utilities
  intl: ^0.19.0
  http: ^1.2.1

  # Local Notifications (Kept for potential future use)
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  workmanager: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
